{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Default capabilities for AEVOICE desktop app",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "core:app:default",
    "core:window:default",
    "core:webview:default",
    "core:path:default",
    "core:event:default",
    "core:tray:default",
    "shell:allow-open",
    "dialog:default",
    "fs:default",
    "fs:allow-read-text-file",
    "fs:allow-write-text-file",
    "fs:allow-read-dir",
    "fs:allow-mkdir",
    "fs:allow-remove",
    "fs:allow-exists",
    "http:default",
    "http:allow-fetch",
    "http:allow-fetch-send",
    "notification:default",
    "notification:allow-request-permission",
    "notification:allow-is-permission-granted",
    "notification:allow-send-notification",
    "store:default",
    "store:allow-load",
    "store:allow-save",
    "store:allow-get",
    "store:allow-set",
    "store:allow-delete",
    "store:allow-clear",
    "store:allow-keys",
    "store:allow-length",
    "store:allow-entries",
    "store:allow-has",
    "process:default",
    "process:allow-exit",
    "process:allow-restart",
    "autostart:default",
    "autostart:allow-enable",
    "autostart:allow-disable",
    "autostart:allow-is-enabled",
    "os:default",
    "os:allow-platform",
    "os:allow-version",
    "clipboard-manager:default",
    "clipboard-manager:allow-read-text",
    "clipboard-manager:allow-write-text"
  ]
}